export const ErrorCode = {
  PATH_NOT_FOUND: "PATH_NOT_FOUND",
  REMOTE_NOT_ACCESSIBLE: "REMOTE_NOT_ACCESSIBLE",
  PERMISSION_DENIED: "PERMISSION_DENIED",
  FILE_LOCKED: "FILE_LOCKED",
  NETWORK_INTERRUPTED: "NETWORK_INTERRUPTED",
  DISK_FULL: "DISK_FULL",
  VERSION_DUPLICATED: "VERSION_DUPLICATED",
  SCAN_FAILED: "SCAN_FAILED",
  COPY_FAILED: "COPY_FAILED",
  DIRECTORY_CREATE_FAILED: "DIRECTORY_CREATE_FAILED",
  NO_FILES: "NO_FILES",
  UNKNOWN: "UNKNOWN",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
